### ISSUE TITLE
Add TSV file of installed formula and their versions

### ISSUE THREAD

**Issue by sjackman** [bcgsc/orca#12]
Please commit to this repo the TSV file used to generate https://tmozgach.github.io/orca/
Just the list of current version. The previous versions aren't needed.

**Comment by sjackman** [comment]
Thanks! https://github.com/bcgsc/orca/blob/master/list_new_orca.tsv
- Please rename the file to `versions.tsv`
- Please remove the first row number column. That should be the default format if you write the TSV using `readr::write_tsv`.
- Please rename column `formula` to `Formula`
- Please rename column `latest` to `Version`

**Comment by sjackman** [comment]
Please add a description and link in the README.md to this TSV file.

**Comment by tmozgach** [comment]
@sjackman changed!

**Comment by sjackman** [comment]
Thanks!
