### ISSUE TITLE
Determine license

### ISSUE THREAD

**Issue by sjackman** [bcgsc/orca#13]
+ [ ] `astral` https://github.com/smirarab/ASTRAL/issues/22
+ [x] `bioawk` Similar to MIT https://github.com/lh3/bioawk/blob/master/README.awk
+ [ ] `cerulean`
+ [ ] `fasttree`
+ [x] `fermi` https://github.com/lh3/fermi/issues/10
+ [ ] `fermi2`https://github.com/lh3/fermi2/issues/3
+ [ ] `fermikit` https://github.com/lh3/fermikit/issues/16
+ [x] `htsbox`
+ [x] `idba`
+ [ ] `kent-tools`
+ [x] `lsd` https://github.com/tothuhien/lsd-0.3beta/issues/4
+ [ ] `pathd8`
+ [ ] `phipack`
+ [ ] `quicktree` https://github.com/khowe/quicktree/issues/2
+ [ ] `trimadap` https://github.com/lh3/trimadap/issues/5

**Comment by tmozgach** [comment]
@sjackman Done! Another formulae don't have a git page.

**Comment by sjackman** [comment]
Thanks, Tanya!
Please open issues for
+ https://github.com/lh3/fermi2
+ https://github.com/lh3/fermikit
+ https://github.com/lh3/htsbox

**Comment by tmozgach** [comment]
@sjackman I cann't open issue for htsbox!

**Comment by sjackman** [comment]
> HTSbox is a fork of early HTSlib

https://github.com/lh3/htsbox/blob/lite/README.md

The license of htslib is MIT. https://github.com/samtools/htslib/blob/develop/LICENSE
