### ISSUE TITLE
Install for HackSeq image

### ISSUE THREAD

**Issue by sjackman** [bcgsc/orca#28]
- [x] nano

- [x] vim

- [x] emacs

- [x] man-db

- [x] methpipe

- [x] less

- [x] bzip2

- [x] xz

- [x] graphviz

- [x] lrsim 

- [x] makefile2graph

- [x] rstudio-server

**Comment by tmozgach** [comment]
Please also brew install less if the command less is not already in the PATH.
And bzip2 and xz if they're not already in the PATH.

**Comment by sjackman** [comment]
The above are all installed.
```
$ which less bzip2 gzip xz
/usr/bin/less
/home/linuxbrew/.linuxbrew/bin/bzip2
/bin/gzip
/home/linuxbrew/.linuxbrew/bin/xz
```

**Comment by tmozgach** [comment]
https://github.com/hackseq/hackseq_2017/issues/33#issuecomment-331976549
