### ISSUE TITLE
ORCA paper

### ISSUE THREAD

**Issue by tmozgach** [bcgsc/orca#32]
**Title:**?
**Format:** Application note (2 pages)
**Deadline:**?
**Journals:**

- [x] _Bioinformatics_ provides a forum for the exchange of information in the fields of computational molecular biology and post-genome bioinformatics, with **emphasis on the documentation of new algorithms and databases** that allows the progress of bioinformatics and biomedical research in a significant manner. (https://academic.oup.com/bioinformatics)

- [ ] _Bioinformatics and Biology Insights_  The journal welcomes **all submissions in the field of bioinformatics** and also submissions dealing with the relationship between bioinformatics and the broader field of biology. Submissions of original research, reviews, tutorials, rapid communications, expert commentaries, letters, application notes, and point–counter-point articles are welcomed for peer review.  (http://insights.sagepub.com/journal.php?pa=aims_and_scope&journal_id=39)

- [ ] _BMC Bioinformatics_ is an open access, peer-reviewed journal  that considers articles **on all aspects** of the development, testing and novel application of computational and statistical methods for the modeling and analysis of all kinds of biological data, as well as other areas of computational biology. (https://bmcbioinformatics.biomedcentral.com/about)

- [ ] _OUP Database_  is platform for the presentation of novel ideas **in database research** surrounding biological information, and aims to help strengthen the bridge between database developers, curators, and users. (https://academic.oup.com/database/pages/About)

- [ ] _Briefings in Bioinformatics_ The journal publishes reviews for the users of databases and analytical tools of contemporary genetics, molecular and systems biology and is unique in **providing practical help and guidance to the non-specialist in computerized methodology**. (https://academic.oup.com/bib/pages/About)

- [ ] _Computational and Structural Biotechnology Journal_ The journal places a strong emphasis on functional and mechanistic understanding of how molecular components in a biological process work together through the application of computational methods. The journal welcomes the submission of manuscripts that meet the general criteria of significance and scientific excellence, and enables the rapid publication of papers under the following categories:
Research articles
Review articles
Mini Reviews
Highlights
Communications
**Software/Web server articles**
(https://www.journals.elsevier.com/computational-and-structural-biotechnology-journal)

- [ ] _EMBNET.JOURNAL_ The main focus of EMBnet.journal is on the latest developments in bioinformatics research, in tools and **resources,** in training and education, and **in standards and best practice.** (https://www.embnet.org/wp/)

- [x]  _GigaScience_ As an open access and open-data journal, we publish ALL research objects (data, software tools and workflows) from **'big data' studies** across the entire spectrum of life and biomedical sciences. (https://academic.oup.com/gigascience)
- [ ]  _eLife_ publishes important research in all areas of the life and biomedical sciences. (https://elifesciences.org/about)
**Structure:**

**Comment by sjackman** [comment]
I believe OUP Database is the journal that Steve suggested: https://academic.oup.com/database

**Comment by tmozgach** [comment]
@sjackman  I have done a small summary of Bioinformatics journals and bolted the main ideas, feel free to add another journals and review my list!

**Comment by sjackman** [comment]
For the literature review, you can compare ORCA to BioContainers http://biocontainers.pro
The Linuxbrew package manager can be compared to Bioconda https://bioconda.github.io
The Spack package manager also has a paper:
https://computation.llnl.gov/projects/spack-hpc-package-manager
http://ieeexplore.ieee.org/document/7832814/
https://doi.org/10.1145/2807591.2807623

**Comment by sjackman** [comment]
Two more possible journals: [GigaScience](https://academic.oup.com/gigascience) and [eLife](https://elifesciences.org/)

**Comment by tmozgach** [comment]
The paper about `biocontaines` can be good example and we can try to target the same journal:

https://academic.oup.com/bioinformatics/article-lookup/doi/10.1093/bioinformatics/btx192

**Comment by tmozgach** [comment]
Bioboxes: https://gigascience.biomedcentral.com/articles/10.1186/s13742-015-0087-0

**Comment by sjackman** [comment]
I've create a GitHub repo for the paper https://github.com/sjackman/orca-paper

**Comment by tmozgach** [comment]
The target journals: Bioinformatics,  GigaScience  (Plan B =) )

**Comment by tmozgach** [comment]
Dugong: https://watermark.silverchair.com/btx554.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAAi8wggIrBgkqhkiG9w0BBwagggIcMIICGAIBADCCAhEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMpIRd-WJ0gsEvLU8yAgEQgIIB4osYlpU_zEhDGmZACecEPgXK9VgLUtCIfG39PHZLNKuM6uGmcrk8bKyBcK3-eB3A27IcLwJL9AXu4FQNYu7fNGUHoAQyTCvK9IRDyGrNkwlK3uxUw6nUdg6ZLSt2k9gXZwMY0zER3_rMcYJGwKuin9BN2NlzIuc3_tt5_51rYyzZCsjzUROiPWWSI0o0Fn0s7g6EBonptMDHJtetRVUQ09L0BdnrvQj1GoVeErIz7ZTg10mDxiXJASt1Cjuwz8cJm7tCq-XjCqECSC8zGGs7TvV_jKKm-IMaeGB6Hs1QRx0gwV8IorgeWkpPoUkFda2NGEwxmf6mxe3AZda2RegWz62lTRy_FZsmacCppE6qaKJx4gn_pCaNAqoUJz-8iXUFCLKTkuYggnGtEE8wI08Qsmt40NLc0m1DyRNrOl4rIrylxiVUyTn2kJPDA6ZkrGTN8KzU4qx61TPp7H2HQc0_dPt8MKVgdRZXdmAOga4Wb5yKlDO1aSEivb8mrIJu42-JsrcmKnqdIGIxsvxXOwuZSJmgxqOf8l9nGOfAGVmBdzHzk8rmEPcDGeyi8LWAH98t1vqvbBydXdnTGgKhphv3tB_p4W2qIg8mPudbuMg6ol9HWeZGH58spHLUcDF8pcB3ygN8

**Comment by tmozgach** [comment]
Main workplace is here: https://github.com/sjackman/orca-paper
