### ISSUE TITLE
Write Documentation

### ISSUE THREAD

**Issue by tmozgach** [bcgsc/orca#34]
How to set up Docker, Docker Swarm, create accounts etc.

**Comment by tmozgach** [comment]
@sjackman do you have any templates, platforms, where and what exactly I should write down?

**Comment by sjackman** [comment]
This is a bit different than a normal software package, but you can take a look these:
https://github.com/linuxbrew/brew
https://github.com/bcgsc/abyss
https://github.com/bcgsc/tigmint

**Comment by tmozgach** [comment]
Outline:
Introduction:
         ORCA(features)
         Container, Docker
Docker installation (just provide links):
         Mac Ox
         Linux
         Windows
Orca installation:
         Pull image, provide the usage (example of Hackseq log in script)
         GUI (links to Xquarts etc.)
Support

**Comment by tmozgach** [comment]
@sjackman could you look at the scratch plan? Anything else to add? Also I am wondering where should I write down this documentation?

**Comment by sjackman** [comment]
You can create files in the `docs` folder of this repo.

**Comment by tmozgach** [comment]
Done!
https://github.com/bcgsc/orca/tree/master/docs
