### ISSUE TITLE
Add jupyter to the ORCA image

### ISSUE THREAD

**Issue by sjackman** [bcgsc/orca#35]
Here's my PR to bottle it.
https://github.com/Linuxbrew/homebrew-core/pull/4600

**Comment by tmozgach** [comment]
@sjackman `brew install  jupyter` is not enough? I didn't understand why you had given me your PR?

**Comment by sjackman** [comment]
There wasn't yet a bottle for `jupyter` when I opened this issue. It's bottled now. `brew install jupyter` is sufficient.

**Comment by tmozgach** [comment]
added
