### ISSUE TITLE
Add missing brewsci/bio formulae to ORCA

### ISSUE THREAD

**Issue by sjackman** [bcgsc/orca#58]
1. abricate
2. bali-phy
3. bandage
4. berokka
5. bonsai
6. cannoli
7. circos
8. consel
9. elph
10. ema
11. emboss
12. exabayes
13. fastp
14. finch-rs
15. flye
16. genome-painter
17. gfalint
18. k8
19. kent-tools
20. kma
21. lastz
22. magic-blast
23. mosdepth
24. mp-est
25. mpboot
26. nextflow
27. orfm
28. phyx
29. porechop
30. portcullis
31. prank
32. quickmerge
33. quicktree
34. r8s
35. rapidnj
36. raxml-ng
37. realphy
38. rtg-tools
39. samclip
40. seq-gen
41. seqkit
42. tigmint
43. transdecoder
44. treepl
45. uniqtag
46. varsim

**Comment by suujia** [comment]
Added the files in this commit: https://github.com/bcgsc/orca/commit/fc2c0150754af8143a14fad7f542bc93b18efc8c

**Comment by sjackman** [comment]
Thanks, Susie!
