### ISSUE TITLE
Problems in including new bottles

### ISSUE THREAD

**Issue by stefcamp** [bcgsc/orca#95]
I successfully installed orca container, however some software are not updated (e.g. flye) and when I try to update them, it looks like the last available release is already present. I would like for example to use a more recent version of "flye" software and I understood I have to use bottles. I found that there is a bottle in linuxbrew for the latest version of the software I am interested in (flye 2.4.2) (https://bintray.com/linuxbrew/bottles-bio/flye/2.4.2) but I cannot find a clear explanation on how to download the binaries and to run them in my container. I downloaded "flye-2.4.2.x86_64_linux.bottle.tar.gz", extracted tar archive and include in orca where the other binaries are saved but this strategy was not successful. Could you please provide an explanation on how to proceed? Additionally, is it possible to request other software to be included in the next orca release?
Thanks a lot
Sincerely
--
Stefano Campanaro

**Comment by sjackman** [comment]
Hi, Stefano. The formulae in ORCA are installed from https://github.com/brewsci/homebrew-bio/tree/master/Formula. Check to see whether the most up-to-date version is present there. You can also check at the web interface https://repology.org/repository/homebrew_tap_brewsci_bio

If the most recent version is found there, run…
```
brew update
brew upgrade flye
```

> Additionally, is it possible to request other software to be included in the next orca release?

Yes, you can open an issue here. The current version of every formula in Brewsci/bio is installed by default.

@lcoombe Is working right now on an updated release of ORCA.
